import './globals.css'
import Modal from '@/components/Modal'
export const metadata = {
  title: 'Trello Clone',
  description: 'Generated by Francies',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#f5f6f8]'>{children}
        <Modal /></body>
    </html>
  )
}
